-- PostgreSQL schema for market_review_trust_db
-- 6 tables, names unchanged
BEGIN;

CREATE TYPE "revie_moderation_status_enum" AS ENUM ('pending','approved','rejected');
CREATE TYPE "review_reports_status_enum" AS ENUM ('pending','approved','rejected');
CREATE TYPE "reviews_status_enum" AS ENUM ('pending','approved','rejected');

CREATE TABLE "product_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "average_rating" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_ratings_product_id" UNIQUE ("product_id")
);
CREATE TABLE "revie_moderation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "status" "revie_moderation_status_enum" NOT NULL DEFAULT 'pending',
  "moderation" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "review_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "review_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "reported_by" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "status" "review_reports_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "rating" SMALLINT DEFAULT NULL,
  "title" varchar(150) NOT NULL,
  "content" text NOT NULL,
  "status" "reviews_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "seller_rating" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" INTEGER NOT NULL,
  "avarage_ratting" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "revie_moderation_fk_review_moderation" ON "revie_moderation" ("review_id");
CREATE INDEX "review_media_fk_review_media_review" ON "review_media" ("review_id");

-- Foreign keys
ALTER TABLE "revie_moderation" ADD CONSTRAINT "fk_review_moderation" FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");
ALTER TABLE "review_media" ADD CONSTRAINT "fk_review_media_review" FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "product_ratings_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_product_ratings_updated_at_update"
BEFORE UPDATE ON "product_ratings"
FOR EACH ROW
EXECUTE FUNCTION "product_ratings_updated_at_update"();
CREATE OR REPLACE FUNCTION "reviews_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_reviews_updated_at_update"
BEFORE UPDATE ON "reviews"
FOR EACH ROW
EXECUTE FUNCTION "reviews_updated_at_update"();

COMMIT;
