CREATE TABLE "search_filters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "field_name" varchar(100) NOT NULL,
  "field_type" varchar(50) NOT NULL,
  "configuration" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "search_filters_uq_search_filter" UNIQUE ("entity_type","field_name")
);
