CREATE TABLE "search_sync_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "attempts" SMALLINT NOT NULL DEFAULT '0',
  "last_error" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
