CREATE TABLE "searche_indexes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "version" INTEGER NOT NULL DEFAULT '1',
  "indexed" BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
