CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" BIGINT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
