CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(10,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "total" decimal(10,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
