CREATE TABLE "checkout_validations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "validation_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "message" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
