CREATE TABLE "checkout_attempts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "attempt_number" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "failure_reason" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "checkout_attempts_checkout_id" UNIQUE ("checkout_id","attempt_number")
);
