CREATE TABLE "inventory_reservations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "expires_at" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
