CREATE TABLE "inventory_movements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "reference_type" varchar(30) NOT NULL,
  "reference_id" INTEGER NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
