CREATE TABLE "inventory_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "quantity" INTEGER NOT NULL,
  "reserved_quantity" INTEGER NOT NULL,
  "available_quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "version" SMALLINT NOT NULL DEFAULT '1',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
