CREATE TABLE "moderation_cases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "case_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "priority" varchar(30) NOT NULL,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
