CREATE TABLE "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
