CREATE TABLE "order_addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "address_type" "order_addresses_address_type_enum" NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "phone" varchar(30) NOT NULL,
  "address_line" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL,
  "country" varchar(100) NOT NULL,
  "location_id" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "order_addresses_order_id" UNIQUE ("order_id","address_type")
);
