CREATE TABLE "product_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "sort_order" INTEGER NOT NULL DEFAULT '0',
  "is_primary" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
