CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "store_id" BIGINT NOT NULL,
  "category_id" INTEGER NOT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "brand" varchar(100) NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "products_slug" UNIQUE ("slug")
);
