CREATE TABLE "product_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) DEFAULT NULL,
  "reason" varchar(255) DEFAULT NULL,
  "changed_by" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
