CREATE TABLE "product_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "sku" varchar(50) NOT NULL,
  "name" varchar(30) NOT NULL,
  "attributes" json DEFAULT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_variants_sku" UNIQUE ("sku")
);
