CREATE TABLE "review_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "reported_by" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "status" "review_reports_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
