CREATE TABLE "review_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
