CREATE TABLE "seller_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "average_rating" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
