CREATE TABLE "seller_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "business_name" varchar(30) DEFAULT NULL,
  "description" text,
  "phone" varchar(16) DEFAULT NULL,
  "mail" varchar(30) DEFAULT NULL,
  "logo_file_id" char(36) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
