CREATE TABLE "seller_actions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "action" varchar(50) NOT NULL,
  "reason" text,
  "performed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
