CREATE TABLE "sellers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "identity_id" char(36) NOT NULL,
  "organization_id" char(36) DEFAULT NULL,
  "display_name" varchar(30) DEFAULT NULL,
  "status" varchar(10) DEFAULT NULL,
  "compliance_status" varchar(30) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
