CREATE TABLE "store_hours" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "day_of_week" SMALLINT DEFAULT NULL,
  "opening_time" time NOT NULL,
  "closing_time" time NOT NULL,
  "is_closed" BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY ("id")
);
