CREATE TABLE "store_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "old_status" varchar(30) NOT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
