-- Consolidated PostgreSQL schema for market_db
BEGIN;

-- ENUM Types
CREATE TYPE "cart_events_event_type_enum" AS ENUM ('CartCreated','CartUpdated','CartItemAdded','CartItemRemoved','CartValidated');
CREATE TYPE "checkout_events_event_type_enum" AS ENUM ('CheckoutStarted','CheckoutValidated','CheckoutFailed','CheckoutConfirmed');
CREATE TYPE "order_addresses_address_type_enum" AS ENUM ('billing','shipping');
CREATE TYPE "review_moderation_status_enum" AS ENUM ('pending','approved','rejected');
CREATE TYPE "review_reports_status_enum" AS ENUM ('pending','approved','rejected');
CREATE TYPE "reviews_status_enum" AS ENUM ('pending','approved','rejected');

-- Helper function for updated_at triggers
CREATE OR REPLACE FUNCTION "update_updated_at_column"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE "sellers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "identity_id" char(36) NOT NULL,
  "organization_id" char(36) DEFAULT NULL,
  "display_name" varchar(30) DEFAULT NULL,
  "status" varchar(10) DEFAULT NULL,
  "compliance_status" varchar(30) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "seller_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "business_name" varchar(30) DEFAULT NULL,
  "description" text,
  "phone" varchar(16) DEFAULT NULL,
  "mail" varchar(30) DEFAULT NULL,
  "logo_file_id" char(36) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "seller_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "old_status" varchar(30) NOT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "seller_actions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "action" varchar(50) NOT NULL,
  "reason" text,
  "performed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "stores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "organization_id" char(36) DEFAULT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "status" varchar(30) DEFAULT NULL,
  "location_id" BIGINT DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "stores_slug" UNIQUE ("slug")
);
CREATE TABLE "store_hours" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "day_of_week" SMALLINT DEFAULT NULL,
  "opening_time" time NOT NULL,
  "closing_time" time NOT NULL,
  "is_closed" BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY ("id")
);
CREATE TABLE "store_settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT NOT NULL,
  "currency" varchar(30) DEFAULT NULL,
  "timezone" varchar(30) DEFAULT NULL,
  "language" varchar(30) DEFAULT NULL,
  "accept_orders" BOOLEAN NOT NULL DEFAULT FALSE,
  "auto_publish_products" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "store_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "old_status" varchar(30) NOT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" INTEGER DEFAULT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "categories_slug" UNIQUE ("slug")
);
CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "store_id" BIGINT NOT NULL,
  "category_id" INTEGER NOT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "brand" varchar(100) NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "products_slug" UNIQUE ("slug")
);
CREATE TABLE "product_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "sku" varchar(50) NOT NULL,
  "name" varchar(30) NOT NULL,
  "attributes" json DEFAULT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_variants_sku" UNIQUE ("sku")
);
CREATE TABLE "product_attributes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "attribute_name" varchar(50) NOT NULL,
  "attribute_value" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "sort_order" INTEGER NOT NULL DEFAULT '0',
  "is_primary" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_prices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "base_price" decimal(10,2) NOT NULL,
  "valid_from" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "valid_until" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) DEFAULT NULL,
  "reason" varchar(255) DEFAULT NULL,
  "changed_by" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "quantity" INTEGER NOT NULL,
  "reserved_quantity" INTEGER NOT NULL,
  "available_quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "version" SMALLINT NOT NULL DEFAULT '1',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_adjustments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "old_quantity" INTEGER NOT NULL,
  "new_quantity" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "adjusted_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_movements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "reference_type" varchar(30) NOT NULL,
  "reference_id" INTEGER NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(10,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "total" decimal(10,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" BIGINT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "cart_item_snapshots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_item_id" INTEGER NOT NULL,
  "product_name" varchar(50) NOT NULL,
  "product_sku" varchar(50) NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "cart_item_snapshots_product_sku" UNIQUE ("product_sku")
);
CREATE TABLE "cart_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "event_type" "cart_events_event_type_enum" NOT NULL,
  "payload" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkouts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(10,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "delivery_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "total" decimal(10,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkout_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkout_attempts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "attempt_number" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "failure_reason" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "checkout_attempts_checkout_id" UNIQUE ("checkout_id","attempt_number")
);
CREATE TABLE "checkout_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "event_type" "checkout_events_event_type_enum" NOT NULL,
  "payload" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkout_validations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "validation_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "message" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_number" INTEGER NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "store_id" BIGINT NOT NULL,
  "status" varchar(30) NOT NULL,
  "payment_status" varchar(30) NOT NULL DEFAULT 'pending',
  "delivery_status" varchar(30) NOT NULL DEFAULT 'pending',
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "delivery_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "total" decimal(12,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "product_name" varchar(30) NOT NULL,
  "sku" varchar(50) NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT '1',
  "unit_price" decimal(12,2) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "address_type" "order_addresses_address_type_enum" NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "phone" varchar(30) NOT NULL,
  "address_line" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL,
  "country" varchar(100) NOT NULL,
  "location_id" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "order_addresses_order_id" UNIQUE ("order_id","address_type")
);
CREATE TABLE "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_payment_references" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "payment_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_reservations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "expires_at" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "store_id" BIGINT NOT NULL,
  "rating" SMALLINT DEFAULT NULL,
  "title" varchar(150) NOT NULL,
  "content" text NOT NULL,
  "status" "reviews_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "review_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "review_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "reported_by" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "status" "review_reports_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "review_moderation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "status" "review_moderation_status_enum" NOT NULL DEFAULT 'pending',
  "moderation" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "average_rating" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_ratings_product_id" UNIQUE ("product_id")
);
CREATE TABLE "seller_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "average_rating" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_moderation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "reason" text,
  "reviewed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_moderation_uq_product_moderation_product" UNIQUE ("product_id")
);
CREATE TABLE "moderation_cases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "case_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "priority" varchar(30) NOT NULL,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "market_configurations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "key" varchar(100) NOT NULL,
  "value" text NOT NULL,
  "environment" varchar(30) NOT NULL,
  "updated_by" INTEGER DEFAULT NULL,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "market_configurations_uq_market_configuration" UNIQUE ("key","environment")
);
CREATE TABLE "market_incidents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "incident_type" varchar(50) NOT NULL,
  "severity" varchar(30) NOT NULL,
  "status" varchar(30) NOT NULL,
  "description" text,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolved_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "search_filters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "field_name" varchar(100) NOT NULL,
  "field_type" varchar(50) NOT NULL,
  "configuration" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "search_filters_uq_search_filter" UNIQUE ("entity_type","field_name")
);
CREATE TABLE "search_sync_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "attempts" SMALLINT NOT NULL DEFAULT '0',
  "last_error" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "search_indexes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "version" INTEGER NOT NULL DEFAULT '1',
  "indexed" BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "seller_profiles_seller_id" ON "seller_profiles" ("seller_id");
CREATE INDEX "stores_seller_id" ON "stores" ("seller_id");
CREATE INDEX "product_attributes_product_id" ON "product_attributes" ("product_id");
CREATE INDEX "product_media_product_id" ON "product_media" ("product_id");
CREATE INDEX "product_status_history_product_id" ON "product_status_history" ("product_id");
CREATE INDEX "inventory_adjustments_inventory_item_id" ON "inventory_adjustments" ("inventory_item_id");
CREATE INDEX "inventory_movements_inventory_item_id" ON "inventory_movements" ("inventory_item_id");
CREATE INDEX "inventory_reservations_inventory_item_id" ON "inventory_reservations" ("inventory_item_id");
CREATE INDEX "cart_events_cart_id" ON "cart_events" ("cart_id");
CREATE INDEX "cart_item_snapshots_cart_item_id" ON "cart_item_snapshots" ("cart_item_id");
CREATE INDEX "cart_items_cart_id" ON "cart_items" ("cart_id");
CREATE INDEX "checkout_events_checkout_id" ON "checkout_events" ("checkout_id");
CREATE INDEX "checkout_items_checkout_id" ON "checkout_items" ("checkout_id");
CREATE INDEX "checkout_validations_checkout_id" ON "checkout_validations" ("checkout_id");
CREATE INDEX "order_payment_references_fk_order_payment_references" ON "order_payment_references" ("order_id");
CREATE INDEX "order_status_history_fk_order_status_history_order" ON "order_status_history" ("order_id");
CREATE INDEX "review_media_fk_review_media_review" ON "review_media" ("review_id");
CREATE INDEX "review_moderation_fk_review_moderation" ON "review_moderation" ("review_id");
-- To build complete index logic:
CREATE INDEX "market_incidents_idx_market_incidents_status" ON "market_incidents" ("status","severity");
CREATE INDEX "product_moderation_idx_product_moderation_product" ON "product_moderation" ("product_id");
CREATE INDEX "seller_actions_idx_seller_actions_seller" ON "seller_actions" ("seller_id");

-- Foreign Keys
-- seller_profiles -> sellers
ALTER TABLE "seller_profiles" ADD CONSTRAINT "seller_profiles_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
-- seller_status_history -> sellers
ALTER TABLE "seller_status_history" ADD CONSTRAINT "seller_status_history_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
-- seller_actions -> sellers
ALTER TABLE "seller_actions" ADD CONSTRAINT "seller_actions_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
-- stores -> sellers
ALTER TABLE "stores" ADD CONSTRAINT "stores_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
-- store_hours -> stores
ALTER TABLE "store_hours" ADD CONSTRAINT "store_hours_ibfk_1" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- store_settings -> stores
ALTER TABLE "store_settings" ADD CONSTRAINT "store_settings_ibfk_1" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- store_status_history -> stores
ALTER TABLE "store_status_history" ADD CONSTRAINT "store_status_history_ibfk_1" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- categories -> categories (parent)
ALTER TABLE "categories" ADD CONSTRAINT "categories_ibfk_1" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");
-- products -> sellers, stores, categories
ALTER TABLE "products" ADD CONSTRAINT "products_seller_fk" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
ALTER TABLE "products" ADD CONSTRAINT "products_store_fk" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
ALTER TABLE "products" ADD CONSTRAINT "products_category_fk" FOREIGN KEY ("category_id") REFERENCES "categories" ("id");
-- product_variants -> products
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- product_attributes -> products
ALTER TABLE "product_attributes" ADD CONSTRAINT "product_attributes_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- product_media -> products
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- product_prices -> products, product_variants
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_variant_fk" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id");
-- product_status_history -> products
ALTER TABLE "product_status_history" ADD CONSTRAINT "product_status_history_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- product_moderation -> products
ALTER TABLE "product_moderation" ADD CONSTRAINT "product_moderation_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- inventory_items -> products, product_variants, stores
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_variant_fk" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id");
ALTER TABLE "inventory_items" ADD CONSTRAINT "inventory_items_store_fk" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- inventory_adjustments -> inventory_items
ALTER TABLE "inventory_adjustments" ADD CONSTRAINT "inventory_adjustments_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");
-- inventory_movements -> inventory_items
ALTER TABLE "inventory_movements" ADD CONSTRAINT "inventory_movements_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");
-- inventory_reservations -> inventory_items, orders
ALTER TABLE "inventory_reservations" ADD CONSTRAINT "inventory_reservations_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");
ALTER TABLE "inventory_reservations" ADD CONSTRAINT "inventory_reservations_order_fk" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
-- cart_items -> carts, products, product_variants, stores
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_ibfk_1" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_variant_fk" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id");
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_store_fk" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- cart_item_snapshots -> cart_items
ALTER TABLE "cart_item_snapshots" ADD CONSTRAINT "cart_item_snapshots_ibfk_1" FOREIGN KEY ("cart_item_id") REFERENCES "cart_items" ("id");
-- cart_events -> carts
ALTER TABLE "cart_events" ADD CONSTRAINT "cart_events_ibfk_1" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");
-- checkouts -> carts
ALTER TABLE "checkouts" ADD CONSTRAINT "checkouts_cart_fk" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");
-- checkout_items -> checkouts, products, product_variants
ALTER TABLE "checkout_items" ADD CONSTRAINT "checkout_items_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
ALTER TABLE "checkout_items" ADD CONSTRAINT "checkout_items_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "checkout_items" ADD CONSTRAINT "checkout_items_variant_fk" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id");
-- checkout_attempts -> checkouts
ALTER TABLE "checkout_attempts" ADD CONSTRAINT "checkout_attempts_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
-- checkout_events -> checkouts
ALTER TABLE "checkout_events" ADD CONSTRAINT "checkout_events_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
-- checkout_validations -> checkouts
ALTER TABLE "checkout_validations" ADD CONSTRAINT "checkout_validations_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
-- orders -> stores
ALTER TABLE "orders" ADD CONSTRAINT "orders_store_fk" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- order_items -> orders, products, product_variants
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_fk" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_variant_fk" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id");
-- order_addresses -> orders
ALTER TABLE "order_addresses" ADD CONSTRAINT "fk_address_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
-- order_status_history -> orders
ALTER TABLE "order_status_history" ADD CONSTRAINT "fk_order_status_history_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
-- order_payment_references -> orders
ALTER TABLE "order_payment_references" ADD CONSTRAINT "fk_order_payment_references" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
-- reviews -> orders, products, stores
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_order_fk" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_store_fk" FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
-- review_media -> reviews
ALTER TABLE "review_media" ADD CONSTRAINT "fk_review_media_review" FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");
-- review_reports -> reviews
ALTER TABLE "review_reports" ADD CONSTRAINT "review_reports_review_fk" FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");
-- review_moderation -> reviews
ALTER TABLE "review_moderation" ADD CONSTRAINT "fk_review_moderation" FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");
-- product_ratings -> products
ALTER TABLE "product_ratings" ADD CONSTRAINT "product_ratings_product_fk" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
-- seller_ratings -> sellers
ALTER TABLE "seller_ratings" ADD CONSTRAINT "seller_ratings_seller_fk" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");

-- Triggers for updated_at columns
CREATE TRIGGER "trg_sellers_updated_at_update" BEFORE UPDATE ON "sellers" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_seller_profiles_updated_at_update" BEFORE UPDATE ON "seller_profiles" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_stores_updated_at_update" BEFORE UPDATE ON "stores" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_store_settings_updated_at_update" BEFORE UPDATE ON "store_settings" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_categories_updated_at_update" BEFORE UPDATE ON "categories" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_products_updated_at_update" BEFORE UPDATE ON "products" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_product_variants_updated_at_update" BEFORE UPDATE ON "product_variants" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_product_prices_updated_at_update" BEFORE UPDATE ON "product_prices" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_inventory_items_updated_at_update" BEFORE UPDATE ON "inventory_items" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_inventory_movements_updated_at_update" BEFORE UPDATE ON "inventory_movements" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_inventory_reservations_updated_at_update" BEFORE UPDATE ON "inventory_reservations" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_carts_updated_at_update" BEFORE UPDATE ON "carts" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_cart_items_updated_at_update" BEFORE UPDATE ON "cart_items" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_checkouts_updated_at_update" BEFORE UPDATE ON "checkouts" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_orders_updated_at_update" BEFORE UPDATE ON "orders" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_order_payment_references_updated_at_update" BEFORE UPDATE ON "order_payment_references" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_reviews_updated_at_update" BEFORE UPDATE ON "reviews" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_product_ratings_updated_at_update" BEFORE UPDATE ON "product_ratings" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_product_moderation_updated_at_update" BEFORE UPDATE ON "product_moderation" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_moderation_cases_updated_at_update" BEFORE UPDATE ON "moderation_cases" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_market_configurations_updated_at_update" BEFORE UPDATE ON "market_configurations" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
CREATE TRIGGER "trg_search_sync_jobs_updated_at_update" BEFORE UPDATE ON "search_sync_jobs" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();

COMMIT;