CREATE TABLE "product_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "average_rating" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_ratings_product_id" UNIQUE ("product_id")
);
