CREATE TABLE "revie_moderation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_id" INTEGER NOT NULL,
  "status" "revie_moderation_status_enum" NOT NULL DEFAULT 'pending',
  "moderation" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
