CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "rating" SMALLINT DEFAULT NULL,
  "title" varchar(150) NOT NULL,
  "content" text NOT NULL,
  "status" "reviews_status_enum" NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
