CREATE TABLE "seller_rating" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" INTEGER NOT NULL,
  "avarage_ratting" decimal(3,2) NOT NULL DEFAULT '0.00',
  "total_reviews" INTEGER NOT NULL DEFAULT '0',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
