CREATE TABLE "cart_item_snapshots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_item_id" INTEGER NOT NULL,
  "produit_name" varchar(50) NOT NULL,
  "product_sku" varchar(50) NOT NULL,
  "unite_price" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "cart_item_snapshots_product_sku" UNIQUE ("product_sku")
);
