CREATE TABLE "cart_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "event_type" "cart_events_event_type_enum" NOT NULL,
  "payload" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
