-- PostgreSQL schema for market_operations_db
-- 5 tables, names unchanged
BEGIN;

CREATE TABLE "market_configurations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "key" varchar(100) NOT NULL,
  "value" text NOT NULL,
  "environment" varchar(30) NOT NULL,
  "updated_by" INTEGER DEFAULT NULL,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "market_configurations_uq_market_configuration" UNIQUE ("key","environment")
);
CREATE TABLE "market_incidents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "incident_type" varchar(50) NOT NULL,
  "severity" varchar(30) NOT NULL,
  "status" varchar(30) NOT NULL,
  "description" text,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolved_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "moderation_cases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "case_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "priority" varchar(30) NOT NULL,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_moderation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "reason" text,
  "reviewed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_moderation_uq_product_moderation_product" UNIQUE ("product_id")
);
CREATE TABLE "seller_actions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" INTEGER NOT NULL,
  "action" varchar(50) NOT NULL,
  "reason" text,
  "performed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "market_incidents_idx_market_incidents_status" ON "market_incidents" ("status","severity");
CREATE INDEX "product_moderation_idx_product_moderation_product" ON "product_moderation" ("product_id");
CREATE INDEX "seller_actions_idx_seller_actions_seller" ON "seller_actions" ("seller_id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "market_configurations_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_market_configurations_updated_at_update"
BEFORE UPDATE ON "market_configurations"
FOR EACH ROW
EXECUTE FUNCTION "market_configurations_updated_at_update"();
CREATE OR REPLACE FUNCTION "moderation_cases_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_moderation_cases_updated_at_update"
BEFORE UPDATE ON "moderation_cases"
FOR EACH ROW
EXECUTE FUNCTION "moderation_cases_updated_at_update"();
CREATE OR REPLACE FUNCTION "product_moderation_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_product_moderation_updated_at_update"
BEFORE UPDATE ON "product_moderation"
FOR EACH ROW
EXECUTE FUNCTION "product_moderation_updated_at_update"();

COMMIT;
