-- PostgreSQL schema for market_order_db
-- 5 tables, names unchanged
BEGIN;

CREATE TYPE "order_addresses_address_type_enum" AS ENUM ('billing','shipping');

CREATE TABLE "order_addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "address_type" "order_addresses_address_type_enum" NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "phone" varchar(30) NOT NULL,
  "address_line" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL,
  "country" varchar(100) NOT NULL,
  "location_id" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "order_addresses_order_id" UNIQUE ("order_id","address_type")
);
CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "product_name" varchar(30) NOT NULL,
  "sku" varchar(50) NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT '1',
  "unit_price" decimal(12,2) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_payment_references" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "payment_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_number" INTEGER NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "payement_status" varchar(30) NOT NULL DEFAULT 'pending',
  "delivery_status" varchar(30) NOT NULL DEFAULT 'pending',
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "delivery_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "total" decimal(12,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "order_payment_references_fk_order_payment_references" ON "order_payment_references" ("order_id");
CREATE INDEX "order_status_history_fk_order_status_history_order" ON "order_status_history" ("order_id");

-- Foreign keys
ALTER TABLE "order_addresses" ADD CONSTRAINT "fk_address_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "order_payment_references" ADD CONSTRAINT "fk_order_payment_references" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
ALTER TABLE "order_status_history" ADD CONSTRAINT "fk_order_status_history_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "order_payment_references_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_order_payment_references_updated_at_update"
BEFORE UPDATE ON "order_payment_references"
FOR EACH ROW
EXECUTE FUNCTION "order_payment_references_updated_at_update"();
CREATE OR REPLACE FUNCTION "orders_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_orders_updated_at_update"
BEFORE UPDATE ON "orders"
FOR EACH ROW
EXECUTE FUNCTION "orders_updated_at_update"();

COMMIT;
