CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "product_name" varchar(30) NOT NULL,
  "sku" varchar(50) NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT '1',
  "unit_price" decimal(12,2) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
