CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_number" INTEGER NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "payement_status" varchar(30) NOT NULL DEFAULT 'pending',
  "delivery_status" varchar(30) NOT NULL DEFAULT 'pending',
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(12,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "delivery_amount" decimal(12,2) NOT NULL DEFAULT '0.00',
  "total" decimal(12,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
