CREATE TABLE "store_settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT NOT NULL,
  "currency" varchar(30) DEFAULT NULL,
  "timezone" varchar(30) DEFAULT NULL,
  "language" varchar(30) DEFAULT NULL,
  "accept_orders" BOOLEAN NOT NULL DEFAULT FALSE,
  "auto_publish_products" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
