CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" INTEGER DEFAULT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "categories_slug" UNIQUE ("slug")
);
