CREATE TABLE "product_prices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "base_price" decimal(10,2) NOT NULL,
  "valid_from" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "valid_until" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
