-- PostgreSQL schema for market_catalog_db
-- 8 tables, names unchanged
BEGIN;

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" INTEGER DEFAULT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "categories_slug" UNIQUE ("slug")
);
CREATE TABLE "creproduct_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "sku" varchar(50) NOT NULL,
  "name" varchar(30) NOT NULL,
  "attributes" json DEFAULT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "creproduct_variants_sku" UNIQUE ("sku")
);
CREATE TABLE "inventory_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" INTEGER DEFAULT NULL,
  "quantity" INTEGER NOT NULL,
  "reserved_quantity" INTEGER NOT NULL,
  "available_quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "version" SMALLINT NOT NULL DEFAULT '1',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_attributes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "attribute_name" varchar(50) NOT NULL,
  "attribute_value" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "file_id" char(36) NOT NULL,
  "media_type" varchar(30) NOT NULL,
  "sort_order" INTEGER NOT NULL DEFAULT '0',
  "is_primary" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_prices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "base_price" decimal(10,2) NOT NULL,
  "valid_from" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "valid_until" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "category_id" INTEGER NOT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "brand" varchar(100) NOT NULL,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "products_slug" UNIQUE ("slug")
);
CREATE TABLE "produit_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "old_status" varchar(30) DEFAULT NULL,
  "new_status" varchar(30) DEFAULT NULL,
  "reason" varchar(255) DEFAULT NULL,
  "changed_by" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "product_attributes_product_id" ON "product_attributes" ("product_id");
CREATE INDEX "product_media_product_id" ON "product_media" ("product_id");
CREATE INDEX "produit_status_history_product_id" ON "produit_status_history" ("product_id");

-- Foreign keys
ALTER TABLE "product_attributes" ADD CONSTRAINT "product_attributes_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "produit_status_history" ADD CONSTRAINT "produit_status_history_ibfk_1" FOREIGN KEY ("product_id") REFERENCES "products" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "categories_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_categories_updated_at_update"
BEFORE UPDATE ON "categories"
FOR EACH ROW
EXECUTE FUNCTION "categories_updated_at_update"();
CREATE OR REPLACE FUNCTION "creproduct_variants_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_creproduct_variants_updated_at_update"
BEFORE UPDATE ON "creproduct_variants"
FOR EACH ROW
EXECUTE FUNCTION "creproduct_variants_updated_at_update"();
CREATE OR REPLACE FUNCTION "inventory_items_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_inventory_items_updated_at_update"
BEFORE UPDATE ON "inventory_items"
FOR EACH ROW
EXECUTE FUNCTION "inventory_items_updated_at_update"();
CREATE OR REPLACE FUNCTION "product_prices_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_product_prices_updated_at_update"
BEFORE UPDATE ON "product_prices"
FOR EACH ROW
EXECUTE FUNCTION "product_prices_updated_at_update"();
CREATE OR REPLACE FUNCTION "products_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_products_updated_at_update"
BEFORE UPDATE ON "products"
FOR EACH ROW
EXECUTE FUNCTION "products_updated_at_update"();

COMMIT;
