-- PostgreSQL schema for market_seller_store_db
-- 7 tables, names unchanged
BEGIN;

CREATE TABLE "seller_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "business_name" varchar(30) DEFAULT NULL,
  "description" text,
  "phone" varchar(16) DEFAULT NULL,
  "mail" varchar(30) DEFAULT NULL,
  "logo_file_id" char(36) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "seller_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" INTEGER NOT NULL,
  "old_status" varchar(30) NOT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "sellers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "identity_id" char(36) NOT NULL,
  "organization_id" char(36) DEFAULT NULL,
  "display_name" varchar(30) DEFAULT NULL,
  "status" varchar(10) DEFAULT NULL,
  "compliance_status" varchar(30) DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "store_hours" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "day_of_week" SMALLINT DEFAULT NULL,
  "opening_time" time NOT NULL,
  "closing_time" time NOT NULL,
  "is_closed" BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY ("id")
);
CREATE TABLE "store_settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT NOT NULL,
  "currency" varchar(30) DEFAULT NULL,
  "timezone" varchar(30) DEFAULT NULL,
  "language" varchar(30) DEFAULT NULL,
  "accept_orders" BOOLEAN NOT NULL DEFAULT FALSE,
  "auto_publish_products" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "store_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "store_id" BIGINT DEFAULT NULL,
  "old_status" varchar(30) NOT NULL,
  "new_status" varchar(30) NOT NULL,
  "reason" text,
  "changed_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "stores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" BIGINT NOT NULL,
  "organization_id" char(36) DEFAULT NULL,
  "name" varchar(30) NOT NULL,
  "slug" varchar(30) DEFAULT NULL,
  "description" text,
  "status" varchar(30) DEFAULT NULL,
  "location_id" BIGINT DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "stores_slug" UNIQUE ("slug")
);

-- Indexes
CREATE INDEX "seller_profiles_seller_id" ON "seller_profiles" ("seller_id");
CREATE INDEX "stores_seller_id" ON "stores" ("seller_id");

-- Foreign keys
ALTER TABLE "seller_profiles" ADD CONSTRAINT "seller_profiles_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");
ALTER TABLE "stores" ADD CONSTRAINT "stores_ibfk_1" FOREIGN KEY ("seller_id") REFERENCES "sellers" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "seller_profiles_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_seller_profiles_updated_at_update"
BEFORE UPDATE ON "seller_profiles"
FOR EACH ROW
EXECUTE FUNCTION "seller_profiles_updated_at_update"();
CREATE OR REPLACE FUNCTION "sellers_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_sellers_updated_at_update"
BEFORE UPDATE ON "sellers"
FOR EACH ROW
EXECUTE FUNCTION "sellers_updated_at_update"();
CREATE OR REPLACE FUNCTION "store_settings_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_store_settings_updated_at_update"
BEFORE UPDATE ON "store_settings"
FOR EACH ROW
EXECUTE FUNCTION "store_settings_updated_at_update"();
CREATE OR REPLACE FUNCTION "stores_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_stores_updated_at_update"
BEFORE UPDATE ON "stores"
FOR EACH ROW
EXECUTE FUNCTION "stores_updated_at_update"();

COMMIT;
