CREATE TABLE "market_incidents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "incident_type" varchar(50) NOT NULL,
  "severity" varchar(30) NOT NULL,
  "status" varchar(30) NOT NULL,
  "description" text,
  "assigned_to" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolved_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
