CREATE TABLE "market_configurations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "key" varchar(100) NOT NULL,
  "value" text NOT NULL,
  "environment" varchar(30) NOT NULL,
  "updated_by" INTEGER DEFAULT NULL,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "market_configurations_uq_market_configuration" UNIQUE ("key","environment")
);
