-- PostgreSQL schema for market_search_db
-- 3 tables, names unchanged
BEGIN;

CREATE TABLE "search_filters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "field_name" varchar(100) NOT NULL,
  "field_type" varchar(50) NOT NULL,
  "configuration" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "search_filters_uq_search_filter" UNIQUE ("entity_type","field_name")
);
CREATE TABLE "search_sync_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "attempts" SMALLINT NOT NULL DEFAULT '0',
  "last_error" text,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "searche_indexes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" INTEGER NOT NULL,
  "version" INTEGER NOT NULL DEFAULT '1',
  "indexed" BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);

-- updated_at triggers
CREATE OR REPLACE FUNCTION "search_sync_jobs_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_search_sync_jobs_updated_at_update"
BEFORE UPDATE ON "search_sync_jobs"
FOR EACH ROW
EXECUTE FUNCTION "search_sync_jobs_updated_at_update"();

COMMIT;
