-- PostgreSQL schema for market_cart_db
-- 4 tables, names unchanged
BEGIN;

CREATE TYPE "cart_events_event_type_enum" AS ENUM ('CartCreated','CartUpdated','CartItemAdded','CartItemRemoved','CartValidated');

CREATE TABLE "cart_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "event_type" "cart_events_event_type_enum" NOT NULL,
  "payload" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "cart_item_snapshots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_item_id" INTEGER NOT NULL,
  "produit_name" varchar(50) NOT NULL,
  "product_sku" varchar(50) NOT NULL,
  "unite_price" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "cart_item_snapshots_product_sku" UNIQUE ("product_sku")
);
CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(10,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "total" decimal(10,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "cart_events_cart_id" ON "cart_events" ("cart_id");
CREATE INDEX "cart_item_snapshots_cart_item_id" ON "cart_item_snapshots" ("cart_item_id");
CREATE INDEX "cart_items_cart_id" ON "cart_items" ("cart_id");

-- Foreign keys
ALTER TABLE "cart_events" ADD CONSTRAINT "cart_events_ibfk_1" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");
ALTER TABLE "cart_item_snapshots" ADD CONSTRAINT "cart_item_snapshots_ibfk_1" FOREIGN KEY ("cart_item_id") REFERENCES "cart_items" ("id");
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_ibfk_1" FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "cart_items_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_cart_items_updated_at_update"
BEFORE UPDATE ON "cart_items"
FOR EACH ROW
EXECUTE FUNCTION "cart_items_updated_at_update"();
CREATE OR REPLACE FUNCTION "carts_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_carts_updated_at_update"
BEFORE UPDATE ON "carts"
FOR EACH ROW
EXECUTE FUNCTION "carts_updated_at_update"();

COMMIT;
