-- PostgreSQL schema for market_inventory_db
-- 4 tables, names unchanged
BEGIN;

CREATE TABLE "inventory_adjustments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "old_quantity" INTEGER NOT NULL,
  "new_quantity" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "adjusted_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "store_id" INTEGER DEFAULT NULL,
  "quantity" INTEGER NOT NULL,
  "reserved_quantity" INTEGER NOT NULL,
  "available_quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "version" SMALLINT NOT NULL DEFAULT '1',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_movements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "refernce_type" varchar(30) NOT NULL,
  "reference_id" INTEGER NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inventory_reservations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "order_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "expires_at" TIMESTAMP DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "inventory_adjustments_inventory_item_id" ON "inventory_adjustments" ("inventory_item_id");
CREATE INDEX "inventory_movements_inventory_item_id" ON "inventory_movements" ("inventory_item_id");
CREATE INDEX "inventory_reservations_inventory_item_id" ON "inventory_reservations" ("inventory_item_id");

-- Foreign keys
ALTER TABLE "inventory_adjustments" ADD CONSTRAINT "inventory_adjustments_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");
ALTER TABLE "inventory_movements" ADD CONSTRAINT "inventory_movements_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");
ALTER TABLE "inventory_reservations" ADD CONSTRAINT "inventory_reservations_ibfk_1" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "inventory_items_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_inventory_items_updated_at_update"
BEFORE UPDATE ON "inventory_items"
FOR EACH ROW
EXECUTE FUNCTION "inventory_items_updated_at_update"();
CREATE OR REPLACE FUNCTION "inventory_movements_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_inventory_movements_updated_at_update"
BEFORE UPDATE ON "inventory_movements"
FOR EACH ROW
EXECUTE FUNCTION "inventory_movements_updated_at_update"();
CREATE OR REPLACE FUNCTION "inventory_reservations_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_inventory_reservations_updated_at_update"
BEFORE UPDATE ON "inventory_reservations"
FOR EACH ROW
EXECUTE FUNCTION "inventory_reservations_updated_at_update"();

COMMIT;
