CREATE TABLE "inventory_adjustments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inventory_item_id" INTEGER NOT NULL,
  "old_quantity" INTEGER NOT NULL,
  "new_quantity" INTEGER NOT NULL,
  "reason" varchar(255) NOT NULL,
  "adjusted_by" INTEGER DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
