-- PostgreSQL schema for market_checkout_db
-- 5 tables, names unchanged
BEGIN;

CREATE TYPE "checkout_events_event_type_enum" AS ENUM ('CheckoutStarted','CheckoutValidated','CheckoutFailed','CheckoutConfirmed');

CREATE TABLE "checkout_attempts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "attempt_number" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "failure_reason" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "checkout_attempts_checkout_id" UNIQUE ("checkout_id","attempt_number")
);
CREATE TABLE "checkout_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "event_type" "checkout_events_event_type_enum" NOT NULL,
  "payload" json DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkout_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkout_validations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_id" INTEGER NOT NULL,
  "validation_type" varchar(50) NOT NULL,
  "status" varchar(30) NOT NULL,
  "message" varchar(255) DEFAULT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "checkouts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" INTEGER NOT NULL,
  "cart_id" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CDF',
  "subtotal" decimal(10,2) NOT NULL DEFAULT '0.00',
  "discount_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "delivery_amount" decimal(10,2) NOT NULL DEFAULT '0.00',
  "total" decimal(10,2) NOT NULL DEFAULT '0.00',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX "checkout_events_checkout_id" ON "checkout_events" ("checkout_id");
CREATE INDEX "checkout_items_checkout_id" ON "checkout_items" ("checkout_id");
CREATE INDEX "checkout_validations_checkout_id" ON "checkout_validations" ("checkout_id");

-- Foreign keys
ALTER TABLE "checkout_attempts" ADD CONSTRAINT "checkout_attempts_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
ALTER TABLE "checkout_events" ADD CONSTRAINT "checkout_events_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
ALTER TABLE "checkout_items" ADD CONSTRAINT "checkout_items_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");
ALTER TABLE "checkout_validations" ADD CONSTRAINT "checkout_validations_ibfk_1" FOREIGN KEY ("checkout_id") REFERENCES "checkouts" ("id");

-- updated_at triggers
CREATE OR REPLACE FUNCTION "checkouts_updated_at_update"()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_checkouts_updated_at_update"
BEFORE UPDATE ON "checkouts"
FOR EACH ROW
EXECUTE FUNCTION "checkouts_updated_at_update"();

COMMIT;
